version: "3.7"
services:
  model_predictor:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: on-failure
    volumes:
      - ../../data/raw_data:/sample_solution/data/raw_data
      - ../../data/train_data:/sample_solution/data/train_data
      - ../../data/model_config:/sample_solution/data/model_config
      - ../../data/captured_data:/sample_solution/data/captured_data
    environment:
      MODEL_CONFIG_PATH: ${MODEL_CONFIG_PATH}
      MODEL_CONFIG_PATH2: ${MODEL_CONFIG_PATH2}
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/sh -c "python src/model_predictor.py --config-path ${MODEL_CONFIG_PATH} --config-path2 ${MODEL_CONFIG_PATH2} --port 8000"
    ports:
      - "8000"
    scale: 6
  nginx:
    image: nginx:latest
    ports:
      - "5040:80"
    volumes:
      - /home/ubuntu/mlops-mara-sample-public/deployment/model_predictor/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - model_predictor